### ISSUE TITLE
For title search, category search.

### ISSUE THREAD

**Issue by lockys** [kevin940726/DcardSearcher#1]
I accidentally see this project about Dcard and the todo list.
There is an API for searching using by Dcard themselves. Maybe you can consider to use it.
https://www.dcard.tw/api/search?search=閃&forum_alias=funny&school=師範大學

BTW, We build a wrapper of Dcard API providing some features like retrieving post data from Dcard. However, I think this module(it's our side project though..) is still premature.
If you are interested, please try it :) We are happy to see your complains and PRs.
https://github.com/lockys/dcard.js

Nice day!

**Comment by kevin940726** [comment]
ya sure, though this project is just a simple tool back then when there is no (as far as I know) such API from Dcard. Actually, Dcard's search had changed just after I made this project lol. So there haven't been updating in this project. Thanks for the advise though.

Wow that seems nice. yeah I will take a look when I get time. Good Work!

**Comment by lockys** [comment]
Thank you  :+1: 
BTW, I love your work about MapleStory Login :smile:, that is pretty cool! 
I played MS when I was junior high haha.
